### ISSUE TITLE
Missing BuildVer local variable file

### ISSUE THREAD

**Issue by timbnr** [br-na-pm/BuildVersion#1]
The variables.var file is referenced in the program package, but missing from the commit
![image](https://user-images.githubusercontent.com/7415686/161832898-44a2fea8-4963-4ae4-93a8-c26d0d6d880a.png)

**Comment by tmatijevich** [comment]
Yes, it is intentionally defined in the package file - thought not actually present in the package, resulting in a "missing" icon.  
On the very first build with pre-build script, the Variables.var file is generated correcting the icon.  

As soon as the var file is added to this repository, it will be tracked regardless of the ignore. We could use [custom configuration settings](https://stackoverflow.com/a/11366713), but this would be required by every collaborator. I would say we could add the var file to the release download, but I would like more feedback before adding it to the repo.

**Comment by timbnr** [comment]
Thanks for the feedback.  First compile I had an AS build error due to this missing var file.  This probably means my script did not successfully complete and generate the file.  Since then, I'm unable to reproduce any problems with the script, and the var file is properly generated  (even if I remove it from the directory before build).
