### ISSUE TITLE
The term 'git' is not recognized as the name of a...

### ISSUE THREAD

**Issue by bolson-BnR** [br-na-pm/BuildVersion#10]
This happened when I sent the project to someone else. It also happens when I try to build in a VM that doesn't have git installed.
![image](https://github.com/br-na-pm/BuildVersion/assets/97972289/3f1b9881-e7ff-4798-b695-4bc742207ccc)

**Comment by tmatijevich** [comment]
Needed try statements after making the change from #7 to run the full script even if `git` was detected as "not recognized"
You should be good to take the latest .ps1 script to repeat your test
