### ISSUE TITLE
License considerations

### ISSUE THREAD

**Issue by ThKit** [br-na-pm/BuildVersion#13]
First of all, thanks a lot for sharing the great work.

However, the GNU GPLv3 makes it impossible (or at least illegal) to use it in any (proprietary) project that is not shared under this license. This is probably the case for most B&R projects. Is this intended? Or might it be an option to switch to a more permissive license (e.g. MIT)?

**Comment by tmatijevich** [comment]
I believe you can use it in your proprietary project, users just cannot distribute a project unless compatible with GPL 3.
I don't think there's much of an argument from my side for or against GPL 3 or MIT.
I think we can move to MIT for the next release (maybe another week).

**Comment by ThKit** [comment]
I'm not an expert in that field, but to my understanding, every project using GPLv3 software code has to be made publicly available in a manner compatible with GPL (the so called copyleft principle). MIT license for example is more permissive in that manner. See [Comparison of free and open-source software licenses - Wikipedia](https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses)
