### ISSUE TITLE
Allow project to build if git is not installed

### ISSUE THREAD

**Issue by bolson-BnR** [br-na-pm/BuildVersion#14]
If a project with BuildVer on it is shared with someone who doesn't have git installed, they will not be able to build the project. I reproduced this by uninstalling git on my own computer and attempting to build:
![image](https://github.com/br-na-pm/BuildVersion/assets/97972289/e37b0739-7bbc-40fd-87a6-a1bb65dfbe7a)

Should the `if($OptionError...` lines instead be `if not($OptionError...`?
![image](https://github.com/br-na-pm/BuildVersion/assets/97972289/48937b1f-db6c-4daa-b248-4b34a16e3016)

**Comment by tmatijevich** [comment]
`exit 1` will error the Automation Studio build.  All `$OptionErrorXXX` flags are [false by default](https://github.com/br-na-pm/BuildVersion/blob/0.0.9/BuildVersion.ps1#L38).

Users without git has been considered (thanks to you 👍 : #10) and implemented ([0.0.8](https://github.com/br-na-pm/BuildVersion/releases/tag/0.0.8)).
Does your PowerShell script have the [try catch blocks](https://github.com/br-na-pm/BuildVersion/blob/0.0.9/BuildVersion.ps1#L120) from the [latest release](https://github.com/br-na-pm/BuildVersion/releases/latest/download/BuildVersion.zip)?

The intended behavior is to throw warnings when git is not installed (line 5 in your console), only update the project information, and leave git information unmodified in the variable declaration file.
Maybe there's a new bug but I thought I tested this use-case.

**Comment by bolson-BnR** [comment]
Oof yeah, I forgot to update past v0.0.7. My fault!
