### ISSUE TITLE
Break build if uncommitted changes exist

### ISSUE THREAD

**Issue by ajw1970** [br-na-pm/BuildVersion#15]
It might be nice to get a build error if there are uncommitted changes.

**Comment by tmatijevich** [comment]
I think this exists.
Can you set `$OptionErrorOnUncommittedChanges` to `$True` in [powershell script](https://github.com/br-na-pm/BuildVersion/blob/0.0.9/BuildVersion.ps1#L42).
It's false by default to not interfere with new users attempting to build.

**Comment by ajw1970** [comment]
Yep, you're right. Thank you.
