### ISSUE TITLE
Change config options with Pre-build arguments rather than hard-coding

### ISSUE THREAD

**Issue by bolson-BnR** [br-na-pm/BuildVersion#16]
Rather than changing the $Options lines of committed code, can they be passed through the build arguments or some other method? So they can be changed while keeping the source code matching this repo

**Comment by tmatijevich** [comment]
In the short-term, see the [develop branch](https://github.com/br-na-pm/BuildVersion/tree/develop).
There, you will have the option to use the `-error_change` switch in the pre-build event (to raise an error instead of a warning is the case of uncommitted changes).
For example,
```
PowerShell -ExecutionPolicy ByPass -File $(WIN32_AS_PROJECT_PATH)\Logical\Tools\BuildVersion\BuildVersion.ps1 $(WIN32_AS_PROJECT_PATH) "$(AS_VERSION)" "$(AS_USER_NAME)" "$(AS_PROJECT_NAME)" "$(AS_CONFIGURATION)" "$(AS_BUILD_MODE)" -error_change
```

**Comment by tmatijevich** [comment]
See [0.1.0](https://github.com/br-na-pm/BuildVersion/releases/tag/0.1.0)
