### ISSUE TITLE
Build Error "array type has incomplete element type"

### ISSUE THREAD

**Issue by ErickZhao1007** [br-na-pm/BuildVersion#18]
Thank you for making this great package.

In one of my applications, two build errors of the same type were triggered: array type has incomplete element type. The file that has these two array types is an automatically generated header file: globalVAR.h. It seems this header file is generated based on the PLC project's Global.var and the tags that caused this error are arrays of global UDT.

The two array type tags from globalVAR.h are:
```
_GLOBAL_RETAIN struct UDT_VesselDetails ShipList[10];
_GLOBAL struct PLCConnected PLC_Connected[31];
```

The global tags that they are generated based on are:
`ShipList : ARRAY[0..9] OF UDT_VesselDetails;`
`PLC_Connected : ARRAY[0..30] OF PLCConnected;`

The UDT are defined:

```
UDT_VesselDetails : 	STRUCT
	Name : STRING[80]; (*Name of vessel*)
	ShipIPString : STRING[80]; (*IP Address of MicroLogix PLC*)
	HasControl : BOOL; (*Selected ship has control of berth*)
	MMSI : DINT; (*MMSI of vessel*)
	LOA : INT; (*LOA of vessel*)
	ShipID : SINT; (*Internal Cavotec ID number of Ship (array index)*)
	Distance : REAL; (*AIS generated distance to berth*)
END_STRUCT;
```

```
PLCConnected : 	STRUCT
	TxEnabled : BOOL;
	Connected : INT;
	WDogValue : DINT;
	PrevWDogValue : DINT;
	TMR_Connected : TON;
	TMR_TxEnabled : TON;
END_STRUCT;
```
The PLC project can compile with no issue without installing this package.

Let me know if I can provide any further information. 👍

**Comment by tmatijevich** [comment]
Thanks for sharing your issue.

I suspect this is related to the [default includes mechanism](https://help.br-automation.com/#/en/4/programming%2Fmixiecandansic%2Fprogrammingmodel_mixiecandansic_include.html) in Automation Studio projects, but I'm not certain.

Can you follow [this link and try out the compiler setting](https://github.com/br-na-pm/BuildVersion/issues/11#issuecomment-1777563806).
You only have to set `-U _DEFAULT_INCLUDES` for the "BuildVer" task (or whatever it's named) in the software configuration "cpu.sw".  Nothing else in the project should have to change.

If that doesn't resolve your issue, can you send a screenshot of the build console showing the info, warning, and error messages and numbers.

**Comment by ErickZhao1007** [comment]
Hi tmatijevich,

Thank you very much for your quick response.

By setting the default include option, the compile error is resolved and I can see that all the buildversion type data is available in the task now.

Thank you very much for creating this cool package, it is very helpful to us 👍

**Comment by ErickZhao1007** [comment]
Issue resolved by adding default include option in the buildversion task's compiler option.

![image](https://github.com/user-attachments/assets/6d5b9d38-d716-42fa-a74f-ebb90d5e3caa)
