### ISSUE TITLE
AS Build Mode Not Detected 

### ISSUE THREAD

**Issue by timbnr** [br-na-pm/BuildVersion#2]
AS build mode is not detected when I use the pre-build script. All other fields are populated.  See screenshots:

![image](https://user-images.githubusercontent.com/7415686/161836336-da5993c6-bbf3-46f9-b13f-2737d48160b7.png)
![image](https://user-images.githubusercontent.com/7415686/161836284-5d9b0f5f-1ccd-43f9-9f08-3c707ba10cb4.png)

**Comment by tmatijevich** [comment]
That's interesting. Thanks for pointing it out.  
Quick isolation test can be `echo Mode: $(AS_BUILD_MODE)` in the pre- or post-build event fields.  
In the latest version of AS I get `Mode: Rebuild`.  
Previous but recent versions of AS I get `Mode: $(AS_BUILD_MODE)`.  
Finally, in older versions of AS I get `Mode: Rebuild` again.  
Appears to have broke for a period of time and is now fixed - I'll catch `$(AS_BUILD_MODE)` and replace with `Unknown`.

**Comment by tmatijevich** [comment]
Exceptions should be handled now in 0.0.2
