### ISSUE TITLE
Spaces in path to project cause problems

### ISSUE THREAD

**Issue by ajw1970** [br-na-pm/BuildVersion#5]
I have spaces in my path: WIN32_AS_PROJECT_PATH

c:\Machine Control\Project will cause problems.

**Comment by tmatijevich** [comment]
Thank you.
It appears Automation Studio build macros already resolve with double quotes.  I manually added double quotes to the arguments leading PowerShell to truncate the argument with multiple quotes at the first whitespace.

All you need to do is update the pre-build event - now updated in README.

I also added an existence check on the logical directory so the build doesn't fail if this situation occurs again.  Update your PowerShell script to add this.

**Comment by ajw1970** [comment]
> All you need to do is update the pre-build event - now updated in README.

I added a space back in to test and works great, thank you again!

**Comment by tmatijevich** [comment]
Now this breaks the version argument.

Arguments without quotations (argument 1 should be "4.11.3.51 SP")
![Without quotations 2022-07-28_11 58 27](https://user-images.githubusercontent.com/33841634/181596257-5c0ffc60-16c6-4820-83be-c544d5702c82.png)

Arguments with quotations (argument 0 should be "C:\New Projects\BuildVersionPrj1")
![With quotations 2022-07-28_11 57 29](https://user-images.githubusercontent.com/33841634/181596368-6321fcf5-a4ce-4b55-a2f8-cf4c7b5ae06a.png)

It's not pretty but I think the quotations just need to be removed for the project name argument.  I'll make a note of it in the installation instructions.

**Comment by ajw1970** [comment]
Ah, thanks. I did end up moving to a path without spaces and not going back to the old path.
