### ISSUE TITLE
Moving package seems to frustrate git

### ISSUE THREAD

**Issue by ajw1970** [br-na-pm/BuildVersion#6]
We moved the BuildVersion package into another Package for organization but now switching between branches throws an error. 

It seems that having the empty folders from the other branch confuses the script.

If we delete the empty folders, we build just fine and the var file is generated. If we don't, it says the var file doesn't exist.

**Comment by tmatijevich** [comment]
It's my understand git does not delete directories, git only operates on files.  
So switching branches with differing directory structures can leave empty directories.  I don't believe this is specific to BuildVersion.

If you move the BuildVersion package, it is necessary to update all configurations' [pre-build event](https://github.com/br-na-pm/BuildVersion#2-create-pre-build-event).  The pre-build event uses a static path to the powershell script.

**Comment by ajw1970** [comment]
> It's my understand git does not delete directories, git only operates on files.

Yes, so we end up with populated folders that our pre-build event is pointed at and also empty folders which it is not pointed at. 

We get an error when we build.

![image](https://user-images.githubusercontent.com/3105267/198671793-c8440cc3-659d-43fd-8c8f-fa06477cc8be.png)

In this case, "src\BR_AS\Logical\BuildVersion" is the populated one.

![image](https://user-images.githubusercontent.com/3105267/198672327-20e5cbbe-6bd2-4b21-878e-56e32e6a2828.png)

We get this error:

`
13	Error	10/28/2022 10:08:10.4638 AM	Object "C:\MachineControl\CoilLines\code\AS\jwelty\src\BR_AS\Logical\BuildVersion\BuildVer\Variables.var" doesn't exist.	9217	Variables.var	C:\MachineControl\CoilLines\code\AS\jwelty\src\BR_AS\Logical\BuildVersion\BuildVer\IEC.prg
`

![image](https://user-images.githubusercontent.com/3105267/198672687-c995700e-3080-4744-9095-680ec5e64a89.png)

All we have to do to fix this is delete the empty folder. 

This leads me to think the script somehow finding the empty folder and not building the .var file?

**Comment by tmatijevich** [comment]
Yes, the script [searches for directories](https://github.com/br-na-pm/BuildVersion/blob/d3bb47bd82c4c4907ce42481ca9921a1c457b42f/BuildVersion.ps1#L71) named ["BuildVer"](https://github.com/br-na-pm/BuildVersion/blob/d3bb47bd82c4c4907ce42481ca9921a1c457b42f/BuildVersion.ps1#L25).

There is currently no check if multiple `BuildVer\` directories are found.  If multiple directories are found, it breaks any generation or write to the `Variables.var` file(s).  I can update the script to throw a warning if multiple directories are found, but it won't solve the build error of missing variables file.  It's a tradeoff of generating variable files in both folders (one correct and one leftover folder), or generating no files.

I would consider using [`git clean -df`](https://git-scm.com/docs/git-clean#Documentation/git-clean.txt) after switching branches to address the additional empty directories.  You can test it with `git clean -df --dry-run`.

**Comment by ajw1970** [comment]
Yep. We've been doing that for now. If your script can locate by a known file that might be a nice addition.
________________________________

**Comment by tmatijevich** [comment]
[New release](https://github.com/br-na-pm/BuildVersion/releases) has loop checking all `$ProgramName` directories for a `.prg` file.  Empty directories will be skipped.  
The first directory with a `.prg` file will be used to generate the `.var` file.  It's not bulletproof but it should cover most cases.
