### ISSUE TITLE
Save BuildVer data when moved out of a repository

### ISSUE THREAD

**Issue by bolson-BnR** [br-na-pm/BuildVersion#7]
Currently, it looks like the script clears its .var file if it finds that it is no longer in a Git repository. (For example, if I exported the project as a zip for someone who isn't on Git) Would it be possible to leave the data as it was in that situation? Or it could leave some data and clear others?

These are the things that matter the most to me:
- **BuildDate and Configuration:** Could the whole `BuildVersionProjectType` structure even be updated because it doesn't depend on Git?
- **Git Tag/Version/Describe:** Lately, I have been displaying that on the HMI instead of the AS hardware config number because it is more likely to be updated regularly

**Comment by tmatijevich** [comment]
Is this what you're thinking?

1. User A builds the project with script from git.  Successfully generates `Variables.var` file.
2. User A archives project.  Archive includes latest `Variables.var` and build script event.
3. User B builds the project from archive without git.  *The `Variables.var` file should be unmodified*.

The archived project still includes the build script event - the beginning of the build script creates a blank `Variables.var` before checking if `git.exe` exists.  This is to avoid project compilation errors but it does overwrite any *good* version information.

I'll see to modified the script to only write a blank `Variables.var` file if no file currently exists.

**Comment by tmatijevich** [comment]
You want `BuildVersion.Git` and `BuildVersion.Project` updated if the user is building with git
but only `BuildVersion.Project` updated if the user if building without git, leaving `BuildVersion.Git` unmodified?

**Comment by tmatijevich** [comment]
See ddb66d1aeff6f54bb649f21070ee2d6187a77c2f, 07e58a4d7c309c87ba8ba3aaaa7ad2e63f3eccef, and 6cace1199ea8171d55e0f03f9075e3e49454114e

**Comment by tmatijevich** [comment]
See [0.0.7](https://github.com/br-na-pm/BuildVersion/releases/tag/0.0.7)
